var GAME_TITLE = "Title";
var GAME_WIDTH = 1440;
var GAME_HEIGHT = 810;
var GAME_NUM_PLAYERS = 1;
var GAME_DESCRIPTION = "Description";
var GAME_WINDOW_BACKGROUND = "black";
var GAME_WINDOW_TEXT_COLOR = "white";